version: '3'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    restart: always
    environment:
      - NODE_ENV=production
      # Add other environment variables if needed
      # - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      # - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    #   - /app/.next
