services:
  nextjs-app:
    container_name: abingdon-antiques
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    restart: always
    volumes:
      - ./public/images:/app/public/images:rw
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
