version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Add any environment variables your app needs
    # env_file:
    #   - .env.production 