services:
  app:
    image: jaredy89/antiques-app:latest
    # Uncomment build section if you want to build locally instead of using the pre-built image
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "9000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Add any environment variables your app needs
    # env_file:
    #   - .env.production
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s 