version: '3'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    restart: always
    volumes:
      - ./public/images:/app/public/images
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    #   - /app/.next
