services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    volumes:
      # Mount source code for development
      - ./src:/app/src
      - ./public:/app/public
    # Command to run in development mode
    command: npm run dev 